# GAME PARAMETERS

WINDOW_WIDTH = 512
WINDOW_HEIGHT = 512

NB_CASE_LINE = 8

BACKGROUND_COLOR = (0, 0, 0)

KEYBOARD_CONTROLL = False

NB_POINTS_ANIMATION = 500

# CASE PARAMETERS

CASE_WIDTH = WINDOW_WIDTH/NB_CASE_LINE
CASE_HEIGHT = WINDOW_HEIGHT/NB_CASE_LINE

WHITE = (234, 235, 239)
BLACK = (121, 130, 147)

SELECTION_COLOR = (0, 0, 255)

POINT_MOVE_WIDTH = CASE_WIDTH/3
POINT_MOVE_HEIGHT = CASE_HEIGHT/3
POSSIBLE_MOVE_COLOR = (255, 0, 0)

# PIECE PARAMETERS

IMAGE_WIDTH = CASE_WIDTH*0.9375
IMAGE_HEIGHT = CASE_HEIGHT*0.9375

PROMOTE_CASE_WIDTH = 60
PROMOTE_CASE_HEIGHT = 60
